//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUICKSIZER.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QUICKSIZER.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Root xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///&lt;Beaminfo&gt;
        ///		&lt;Name&gt;CHS 114.3x10.0&lt;/Name&gt;
        ///		&lt;Weight&gt;25.7&lt;/Weight&gt;
        ///		&lt;Length&gt;1&lt;/Length&gt;
        ///		&lt;Resistance&gt;1120&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;CHS 114.3x10.0&lt;/Name&gt;
        ///		&lt;Weight&gt;25.7&lt;/Weight&gt;
        ///		&lt;Length&gt;1.5&lt;/Length&gt;
        ///		&lt;Resistance&gt;1060&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;CHS 114.3x10.0&lt;/Name&gt;
        ///		&lt;Weight&gt;25.7&lt;/Weight&gt;
        ///		&lt;Length&gt;2&lt;/Length&gt;
        ///		&lt;Resistance&gt;983&lt;/Resist [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CHS_NRd {
            get {
                return ResourceManager.GetString("CHS_NRd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Root xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///&lt;Beaminfo&gt;
        ///		&lt;Name&gt;EHS 150x75x4.0&lt;/Name&gt;
        ///		&lt;Weight&gt;10.7&lt;/Weight&gt;
        ///		&lt;Length&gt;1&lt;/Length&gt;
        ///		&lt;Resistance&gt;404&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;EHS 150x75x4.0&lt;/Name&gt;
        ///		&lt;Weight&gt;10.7&lt;/Weight&gt;
        ///		&lt;Length&gt;1.5&lt;/Length&gt;
        ///		&lt;Resistance&gt;368&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;EHS 150x75x4.0&lt;/Name&gt;
        ///		&lt;Weight&gt;10.7&lt;/Weight&gt;
        ///		&lt;Length&gt;2&lt;/Length&gt;
        ///		&lt;Resistance&gt;313&lt;/Resistan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EHS_NRd {
            get {
                return ResourceManager.GetString("EHS_NRd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Root xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;HE 100 A&lt;/Name&gt;
        ///		&lt;Weight&gt;16.7&lt;/Weight&gt;
        ///		&lt;Length&gt;1.0&lt;/Length&gt;
        ///		&lt;Resistance&gt;625&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;HE 100 AA&lt;/Name&gt;
        ///		&lt;Weight&gt;12.2&lt;/Weight&gt;
        ///		&lt;Length&gt;1.0&lt;/Length&gt;
        ///		&lt;Resistance&gt;455&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;HE 1000 A*&lt;/Name&gt;
        ///		&lt;Weight&gt;272&lt;/Weight&gt;
        ///		&lt;Length&gt;1.0&lt;/Length&gt;
        ///		&lt;Resistance&gt;10600&lt;/Resistance&gt;
        ///	&lt;/B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HEA_NRd {
            get {
                return ResourceManager.GetString("HEA_NRd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Root xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;HE 100 A&lt;/Name&gt;
        ///		&lt;Weight&gt;16.7&lt;/Weight&gt;
        ///		&lt;Length&gt;1&lt;/Length&gt;
        ///		&lt;NRd&gt;625&lt;/NRd&gt;
        ///		&lt;MRd&gt;29.5&lt;/MRd&gt;
        ///		&lt;VRd&gt;154&lt;/VRd&gt;
        ///		&lt;Inertia&gt;349&lt;/Inertia&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;HE 100 AA&lt;/Name&gt;
        ///		&lt;Weight&gt;12.2&lt;/Weight&gt;
        ///		&lt;Length&gt;1&lt;/Length&gt;
        ///		&lt;NRd&gt;455&lt;/NRd&gt;
        ///		&lt;MRd&gt;20.7&lt;/MRd&gt;
        ///		&lt;VRd&gt;126&lt;/VRd&gt;
        ///		&lt;Inertia&gt;236&lt;/Inertia&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;HE 1000 A*&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HEA_NRd1 {
            get {
                return ResourceManager.GetString("HEA_NRd1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Root xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;HE 100 B&lt;/Name&gt;
        ///		&lt;Weight&gt;20.4&lt;/Weight&gt;
        ///		&lt;Length&gt;1.0&lt;/Length&gt;
        ///		&lt;Resistance&gt;769&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;HE 100 C&lt;/Name&gt;
        ///		&lt;Weight&gt;30.9&lt;/Weight&gt;
        ///		&lt;Length&gt;1.0&lt;/Length&gt;
        ///		&lt;Resistance&gt;1180&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;HE 100 M&lt;/Name&gt;
        ///		&lt;Weight&gt;41.8&lt;/Weight&gt;
        ///		&lt;Length&gt;1.0&lt;/Length&gt;
        ///		&lt;Resistance&gt;1580&lt;/Resistance&gt;
        ///	&lt;/Bea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HEB_NRd {
            get {
                return ResourceManager.GetString("HEB_NRd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Root xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;IPE 100&lt;/Name&gt;
        ///		&lt;Weight&gt;8.1&lt;/Weight&gt;
        ///		&lt;Length&gt;1&lt;/Length&gt;
        ///		&lt;Resistance&gt;206&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;IPE 120&lt;/Name&gt;
        ///		&lt;Weight&gt;10.4&lt;/Weight&gt;
        ///		&lt;Length&gt;1&lt;/Length&gt;
        ///		&lt;Resistance&gt;309&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;IPE 140&lt;/Name&gt;
        ///		&lt;Weight&gt;12.9&lt;/Weight&gt;
        ///		&lt;Length&gt;1&lt;/Length&gt;
        ///		&lt;Resistance&gt;424&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Be [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IPE_NRd {
            get {
                return ResourceManager.GetString("IPE_NRd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Root xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;100x100x11&lt;/Name&gt;
        ///		&lt;Weight&gt;16.4065&lt;/Weight&gt;
        ///		&lt;Length&gt;1&lt;/Length&gt;
        ///		&lt;Resistance&gt;527&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;100x100x12&lt;/Name&gt;
        ///		&lt;Weight&gt;17.8195&lt;/Weight&gt;
        ///		&lt;Length&gt;1&lt;/Length&gt;
        ///		&lt;Resistance&gt;573&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;100x100x13&lt;/Name&gt;
        ///		&lt;Weight&gt;19.2325&lt;/Weight&gt;
        ///		&lt;Length&gt;1&lt;/Length&gt;
        ///		&lt;Resistance&gt;618&lt;/Resistance&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lequal_NRd {
            get {
                return ResourceManager.GetString("Lequal_NRd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Root xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///&lt;Beaminfo&gt;
        ///		&lt;Name&gt;PFC 100x50x10&lt;/Name&gt;
        ///		&lt;Weight&gt;10&lt;/Weight&gt;
        ///		&lt;Length&gt;1&lt;/Length&gt;
        ///		&lt;Resistance&gt;297&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;PFC 100x50x10&lt;/Name&gt;
        ///		&lt;Weight&gt;10&lt;/Weight&gt;
        ///		&lt;Length&gt;1.5&lt;/Length&gt;
        ///		&lt;Resistance&gt;191&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;PFC 100x50x10&lt;/Name&gt;
        ///		&lt;Weight&gt;10&lt;/Weight&gt;
        ///		&lt;Length&gt;2&lt;/Length&gt;
        ///		&lt;Resistance&gt;124&lt;/Resistance&gt;
        ///	&lt;/B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PFC_NRd {
            get {
                return ResourceManager.GetString("PFC_NRd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Root xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;RHS 100x50x10.0&lt;/Name&gt;
        ///		&lt;Weight&gt;19.6&lt;/Weight&gt;
        ///		&lt;Length&gt;1&lt;/Length&gt;
        ///		&lt;Resistance&gt;732&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;RHS 100x50x10.0&lt;/Name&gt;
        ///		&lt;Weight&gt;19.6&lt;/Weight&gt;
        ///		&lt;Length&gt;1.5&lt;/Length&gt;
        ///		&lt;Resistance&gt;521&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;RHS 100x50x10.0&lt;/Name&gt;
        ///		&lt;Weight&gt;19.6&lt;/Weight&gt;
        ///		&lt;Length&gt;2&lt;/Length&gt;
        ///		&lt;Resistance&gt;337&lt;/Resi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RHS_NRd {
            get {
                return ResourceManager.GetString("RHS_NRd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Root xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///&lt;Beaminfo&gt;
        ///		&lt;Name&gt;SHS 100x100x10.0&lt;/Name&gt;
        ///		&lt;Weight&gt;27.4&lt;/Weight&gt;
        ///		&lt;Length&gt;1&lt;/Length&gt;
        ///		&lt;Resistance&gt;1190&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;SHS 100x100x10.0&lt;/Name&gt;
        ///		&lt;Weight&gt;27.4&lt;/Weight&gt;
        ///		&lt;Length&gt;1.5&lt;/Length&gt;
        ///		&lt;Resistance&gt;1130&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;SHS 100x100x10.0&lt;/Name&gt;
        ///		&lt;Weight&gt;27.4&lt;/Weight&gt;
        ///		&lt;Length&gt;2&lt;/Length&gt;
        ///		&lt;Resistance&gt;1040&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SHS_NRd {
            get {
                return ResourceManager.GetString("SHS_NRd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Root xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///&lt;Beaminfo&gt;
        ///		&lt;Name&gt;UB 1000 x 400 x 296*&lt;/Name&gt;
        ///		&lt;Weight&gt;296&lt;/Weight&gt;
        ///		&lt;Length&gt;1&lt;/Length&gt;
        ///		&lt;Resistance&gt;11600&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;UB 1000 x 400 x 296*&lt;/Name&gt;
        ///		&lt;Weight&gt;296&lt;/Weight&gt;
        ///		&lt;Length&gt;1.5&lt;/Length&gt;
        ///		&lt;Resistance&gt;11600&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;UB 1000 x 400 x 296*&lt;/Name&gt;
        ///		&lt;Weight&gt;296&lt;/Weight&gt;
        ///		&lt;Length&gt;2&lt;/Length&gt;
        ///		&lt;Resis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UB_NRd {
            get {
                return ResourceManager.GetString("UB_NRd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Root xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;UBP 203 x 203 x 45&lt;/Name&gt;
        ///		&lt;Weight&gt;45&lt;/Weight&gt;
        ///		&lt;Length&gt;1&lt;/Length&gt;
        ///		&lt;Resistance&gt;1960&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;UBP 203 x 203 x 45&lt;/Name&gt;
        ///		&lt;Weight&gt;45&lt;/Weight&gt;
        ///		&lt;Length&gt;1.5&lt;/Length&gt;
        ///		&lt;Resistance&gt;1820&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;UBP 203 x 203 x 45&lt;/Name&gt;
        ///		&lt;Weight&gt;45&lt;/Weight&gt;
        ///		&lt;Length&gt;2&lt;/Length&gt;
        ///		&lt;Resistance&gt;1680 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UBP_NRd {
            get {
                return ResourceManager.GetString("UBP_NRd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Root xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;UC 152 x 152 x 23&lt;/Name&gt;
        ///		&lt;Weight&gt;23&lt;/Weight&gt;
        ///		&lt;Length&gt;1&lt;/Length&gt;
        ///		&lt;Resistance&gt;955&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;UC 152 x 152 x 23&lt;/Name&gt;
        ///		&lt;Weight&gt;23&lt;/Weight&gt;
        ///		&lt;Length&gt;1.5&lt;/Length&gt;
        ///		&lt;Resistance&gt;856&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;UC 152 x 152 x 23&lt;/Name&gt;
        ///		&lt;Weight&gt;23&lt;/Weight&gt;
        ///		&lt;Length&gt;2&lt;/Length&gt;
        ///		&lt;Resistance&gt;746&lt;/Resi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UC_NRd {
            get {
                return ResourceManager.GetString("UC_NRd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Root xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;UPE 100&lt;/Name&gt;
        ///		&lt;Weight&gt;9.82&lt;/Weight&gt;
        ///		&lt;Length&gt;1&lt;/Length&gt;
        ///		&lt;Resistance&gt;308&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;UPE 100&lt;/Name&gt;
        ///		&lt;Weight&gt;9.82&lt;/Weight&gt;
        ///		&lt;Length&gt;1.5&lt;/Length&gt;
        ///		&lt;Resistance&gt;210&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	&lt;Beaminfo&gt;
        ///		&lt;Name&gt;UPE 100&lt;/Name&gt;
        ///		&lt;Weight&gt;9.82&lt;/Weight&gt;
        ///		&lt;Length&gt;2&lt;/Length&gt;
        ///		&lt;Resistance&gt;140&lt;/Resistance&gt;
        ///	&lt;/Beaminfo&gt;
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UPE_UPN_NRd {
            get {
                return ResourceManager.GetString("UPE_UPN_NRd", resourceCulture);
            }
        }
    }
}
